services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jg-employee
    ports:
      - "3005:3000"
    restart: always
    environment:
      - NODE_ENV=production
